apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  instances: 1
  externalAccess:
    enabled: False
  externalDatabase:
    enabled: True

  #https://github.com/keycloak/keycloak-operator/issues/426
  # keycloakDeploymentSpec:
  #   experimental:
  #     env:
  #       - name: DB_ADDR
  #         valueFrom:
  #           secretKeyRef:
  #             name: keycloak-db-secret
  #             key: POSTGRES_EXTERNAL_ADDRESS
  #       - name: KEYCLOAK_POSTGRESQL_SERVICE_HOST
  #         valueFrom:
  #           secretKeyRef:
  #             name: keycloak-db-secret
  #             key: POSTGRES_EXTERNAL_ADDRESS
