apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-ca
  namespace: logging
spec:
  isCA: true
  commonName: root-ca
  secretName: root-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
