# Allocate smaller chunks of memory per pod.
elasticsearchHosts: "https://elasticsearch-master:9200"

resources:
  requests:
    cpu: "100m"
    memory: "512M"
  limits:
    cpu: "1000m"
    memory: "1G"

fullnameOverride: "kibana"

extraEnvs:
  # https://github.com/elastic/helm-charts/issues/1334
  - name: "ELASTICSEARCH_USERNAME"
    value: elastic
    # valueFrom:
    #   secretKeyRef:
    #     name: elastic-credentials
    #     key: username
  - name: "ELASTICSEARCH_PASSWORD"
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: password
  - name: "KIBANA_ENCRYPTION_KEY"
    valueFrom:
      secretKeyRef:
        name: kibana-credentials
        key: encryptionkey

kibanaConfig:
  kibana.yml: |
    server:
      publicBaseUrl: "https://logs.fdk.codes"
    elasticsearch:
      ssl:
        key: /usr/share/kibana/config/certs/tls.key
        certificate: /usr/share/kibana/config/certs/tls.crt
        certificateAuthorities: /usr/share/kibana/config/certs/ca.crt
        verificationMode: full
    xpack.security.encryptionKey: ${KIBANA_ENCRYPTION_KEY}
    xpack.reporting.encryptionKey: ${KIBANA_ENCRYPTION_KEY}
    xpack.encryptedSavedObjects.encryptionKey: ${KIBANA_ENCRYPTION_KEY}
    telemetry.enabled: false

secretMounts:
  - name: kibana-certificates
    secretName: kibana-cert
    path: /usr/share/kibana/config/certs
