# Allocate smaller chunks of memory per pod.
elasticsearchHosts: "https://elasticsearch-master:9200"

resources:
  requests:
    cpu: "100m"
    memory: "512M"
  limits:
    cpu: "1000m"
    memory: "1G"

fullnameOverride: "kibana"

extraEnvs:
  - name: "ELASTICSEARCH_USERNAME"
    value: elastic
  - name: "ELASTICSEARCH_PASSWORD"
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: password

kibanaConfig:
  kibana.yml: |
    server.publicBaseUrl: "https://logs.fdk.codes"
    # server.ssl.enabled: true
    # server.ssl.certificate: /usr/share/kibana/config/certs/tls.crt
    # server.ssl.key: /usr/share/kibana/config/certs/tls.key
    elasticsearch:
      hosts: ${ELASTICSEARCH_HOSTS}
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}
      # ssl:
      #   key: /usr/share/kibana/config/certs/tls.key
      #   certificate: /usr/share/kibana/config/certs/tls.crt
      #   certificateAuthorities: /usr/share/kibana/config/certs/ca.crt
      #   verificationMode: certificate

secretMounts:
  - name: elastic-certificates
    secretName: es-cert
    path: /usr/share/kibana/config/certs
    defaultMode: 0755
