apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fdk-codes
  namespace: istio-ingress
spec:
  secretName: fdk-codes-tls
  issuerRef:
    name: letsencrypt-prod
  dnsNames:
    - "*.fdk.codes"
    - fdk.codes
