apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: postgres
  namespace: postgres

spec:
  replicas: 3
  image: postgres:14.2
  port: 5432

  database:
    size: 200Mi
    storageClassName: local-path
    volumeMount: /var/lib/postgresql/data

  customConfig: postgres-conf

  env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-credentials
          key: superUserPassword

    - name: POSTGRES_REPLICATION_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-credentials
          key: replicationUserPassword

    - name: POSTGRES_KEYCLOAK_USER
      valueFrom:
        secretKeyRef:
          name: postgres-credentials
          key: keycloakUser

    - name: POSTGRES_KEYCLOAK_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-credentials
          key: keycloakPassword

    - name: POSTGRES_KEYCLOAK_DB
      value: keycloak

  resources:
    requests:
      cpu: "100m"
      memory: "100Mi"
    limits:
      cpu: "1"
      memory: "500Mi"
